=== gokulprakash22/JAVA_Exercises/mycodes/Components/invoice.dtd
<!ELEMENT invoice (customer,items,invdetails)>
<!ELEMENT customer (customerno,customername,customeraddress,customeremail,customerphone)>
<!ELEMENT customerno (#PCDATA)>
<!ELEMENT customername (#PCDATA)>
<!ELEMENT customeraddress (#PCDATA)>
<!ELEMENT customeremail (#PCDATA)>
<!ELEMENT customerphone (#PCDATA)> 
<!ELEMENT items (item+)>
<!ELEMENT item (itemno,itemdescription,itemunit,itemprice,itemqty,itemtotal)>
<!ELEMENT itemno (#PCDATA)>
<!ELEMENT itemdescription (#PCDATA)>
<!ELEMENT itemunit (#PCDATA)> 
<!ELEMENT itemprice (#PCDATA)>
<!ELEMENT itemqty (#PCDATA)>
<!ELEMENT itemtotal (#PCDATA)>
<!ELEMENT invdetails (invno,date,total)>
<!ELEMENT invno (#PCDATA)> 
<!ELEMENT date (#PCDATA)>
<!ELEMENT total (#PCDATA)>

=== gokulprakash22/JAVA_Exercises/mycodes/Components/103.xml
<!DOCTYPE invoice SYSTEM "invoice.dtd"><invoice><customer><customerno>2</customerno><customername>Somu</customername><customeraddress>Delhi</customeraddress><customeremail>somu@gmail.com</customeremail><customerphone>9876512340</customerphone></customer><items><item><itemno>1001</itemno><itemdescription>Parle - G</itemdescription><itemunit>1 pkt</itemunit><itemprice>10</itemprice><itemqty>2</itemqty><itemtotal>20.0</itemtotal></item><item><itemno>1005</itemno><itemdescription>Milk</itemdescription><itemunit>1/2 Litre</itemunit><itemprice>25</itemprice><itemqty>5</itemqty><itemtotal>125.0</itemtotal></item></items><invdetails><invno>103</invno><date>23-03-2021 07:36:30</date><total>145.0</total></invdetails></invoice>

=== gokulprakash22/JAVA_Exercises/myassignments/Components/104.xml
<!DOCTYPE invoice SYSTEM "invoice.dtd"><invoice><customer><customerno>1</customerno><customername>Somu</customername><customeraddress>Chennai</customeraddress><customeremail>somu@gmail.com</customeremail><customerphone>9876543210</customerphone><invoiceno>104</invoiceno></customer><items><item><itemno>1005</itemno><itemdescription>Milk</itemdescription><itemprice>25</itemprice><itemqty>4</itemqty><itemunit>1/2 Litre</itemunit><itemtotal>100</itemtotal></item><item><itemno>1004</itemno><itemdescription>Tomato</itemdescription><itemprice>100</itemprice><itemqty>3</itemqty><itemunit>1kg</itemunit><itemtotal>300</itemtotal></item><item><itemno>1003</itemno><itemdescription>Onion</itemdescription><itemprice>150</itemprice><itemqty>2</itemqty><itemunit>1kg</itemunit><itemtotal>300</itemtotal></item></items></invoice>

=== gokulprakash22/JAVA_Exercises/myassignments/ShoppingCartServlet/results/145.xml
<!DOCTYPE invoice SYSTEM "invoice.dtd"><invoice><customer><customerno>4</customerno><customername>Gokul Prakash</customername><customeraddress>Chennai</customeraddress><customeremail>gokulprakash22@gmail.com</customeremail><customerphone>+918946069629</customerphone></customer><items><item><itemno>1003</itemno><itemdescription>Onion</itemdescription><itemunit>1kg</itemunit><itemprice>150</itemprice><itemqty>2</itemqty><itemtotal>300.0</itemtotal></item><item><itemno>1006</itemno><itemdescription>Orange</itemdescription><itemunit>1kg</itemunit><itemprice>100</itemprice><itemqty>3</itemqty><itemtotal>300.0</itemtotal></item><item><itemno>1001</itemno><itemdescription>Parle-G</itemdescription><itemunit>1pkt</itemunit><itemprice>10</itemprice><itemqty>1</itemqty><itemtotal>10.0</itemtotal></item><item><itemno>1002</itemno><itemdescription>MilkBikis</itemdescription><itemunit>1pkt</itemunit><itemprice>10</itemprice><itemqty>1</itemqty><itemtotal>10.0</itemtotal></item></items><invdetails><invno>145</invno><date>2021-03-31</date><total>620.0</total></invdetails></invoice>

=== gokulprakash22/JAVA_Exercises/myassignments/Components/105.xml
<!DOCTYPE invoice SYSTEM "invoice.dtd"><invoice><customer><customerno>2</customerno><customername>Mani</customername><customeraddress>Delhi</customeraddress><customeremail>mani@gmail.com</customeremail><customerphone>9876501234</customerphone></customer><items><item><itemno>1002</itemno><itemdescription>MilkBikis</itemdescription><itemunit>1 pkt</itemunit><itemprice>10</itemprice><itemqty>2</itemqty><itemtotal>20.0</itemtotal></item><item><itemno>1001</itemno><itemdescription>Parle - G</itemdescription><itemunit>1 pkt</itemunit><itemprice>10</itemprice><itemqty>2</itemqty><itemtotal>20.0</itemtotal></item></items><invdetails><invno>105</invno><date>2021-03-22</date><total>40.0</total></invdetails></invoice>
